version: '3.2'

services:
  dst-test:
    build: .
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    tty: true
    ports:
      - ${APP_PORT:-80}:80
      - 443:443
    volumes:
      - ./:/app
      # nginx configs
      - ./server.conf:/etc/nginx/conf.d/server.conf
    networks:
      - app-network
    depends_on:
      - mysql
      - dst-test

  mysql:
    image: mysql:8.0.16
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dsttest}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    ports:
      - ${DB_PORT:-3306}:3306
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin}
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: always
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
